// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QueenZone.Data;

#nullable disable

namespace QueenZone.Data.Migrations
{
    [DbContext(typeof(QueenZoneDbContext))]
    [Migration("20260720030712_SyncPhotoSubmissionModel")]
    partial class SyncPhotoSubmissionModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QueenZone.Data.Entities.ForumPollEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ClosesAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMultiChoice")
                        .HasColumnType("bit");

                    b.Property<int>("LegacyTopicId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxChoices")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<long>("ThreadId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LegacyTopicId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ForumPolls_LegacyTopicId");

                    b.HasIndex("ThreadId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ForumPolls_ThreadId");

                    b.ToTable("ForumPolls", (string)null);
                });

            modelBuilder.Entity("QueenZone.Data.Entities.ForumPollOptionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PollId", "DisplayOrder")
                        .HasDatabaseName("IX_ForumPollOptions_PollId_DisplayOrder");

                    b.ToTable("ForumPollOptions", (string)null);
                });

            modelBuilder.Entity("QueenZone.Data.Entities.ForumPollVoteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PollId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("VotedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.HasIndex("PollId", "MemberAccountId", "OptionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ForumPollVotes_Poll_Member_Option");

                    b.ToTable("ForumPollVotes", (string)null);
                });

            modelBuilder.Entity("QueenZone.Data.Entities.ForumPostAttachmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("DownloadCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("LegacyPostId")
                        .HasColumnType("int");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("PostId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("LegacyPostId")
                        .HasDatabaseName("IX_ForumPostAttachments_LegacyPostId");

                    b.HasIndex("PostId")
                        .HasDatabaseName("IX_ForumPostAttachments_PostId");

                    b.ToTable("ForumPostAttachments", (string)null);
                });

            modelBuilder.Entity("QueenZone.Data.Entities.MemberAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("LinkedLegacyUserId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("IX_MemberAccounts_NormalizedEmail");

                    b.ToTable("MemberAccounts", (string)null);
                });

            modelBuilder.Entity("QueenZone.Data.Entities.MemberExternalLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MemberAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("MemberAccountId");

                    b.HasIndex("Provider", "ProviderKey")
                        .IsUnique()
                        .HasDatabaseName("IX_MemberExternalLogins_Provider_ProviderKey");

                    b.ToTable("MemberExternalLogins", (string)null);
                });

            modelBuilder.Entity("QueenZone.Data.Entities.ModernForumCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSynthetic")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LegacyForumId")
                        .HasColumnType("int");

                    b.Property<int>("LegacyPostCount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LegacyForumId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ModernForumCategory_LegacyForumId");

                    b.ToTable("ModernForumCategory", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("QueenZone.Data.Entities.ModernForumPostEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AttachCount")
                        .HasColumnType("int");

                    b.Property<string>("Attachment")
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("AuthorDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("AuthorJoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AuthorLegacyUserId")
                        .HasColumnType("int");

                    b.Property<Guid?>("AuthorMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AuthorPostCount")
                        .HasColumnType("int");

                    b.Property<bool?>("AuthorUserValidated")
                        .HasColumnType("bit");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8000)");

                    b.Property<int>("EditCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileSize")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("LegacyDiscography")
                        .HasColumnType("tinyint");

                    b.Property<int>("LegacyForumId")
                        .HasColumnType("int");

                    b.Property<int>("LegacyPostId")
                        .HasColumnType("int");

                    b.Property<int>("LegacyThreadTopicId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PostedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SignatureHtml")
                        .HasMaxLength(8000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8000)");

                    b.Property<long>("ThreadId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorMemberId")
                        .HasDatabaseName("IX_ModernForumPost_AuthorMemberId");

                    b.HasIndex("LegacyPostId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ModernForumPost_LegacyPostId");

                    b.HasIndex("ThreadId");

                    b.ToTable("ModernForumPost", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("QueenZone.Data.Entities.ModernForumThreadEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLegacyTopicStarter")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSticky")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastActivityAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("LegacyDiscography")
                        .HasColumnType("tinyint");

                    b.Property<int>("LegacyForumId")
                        .HasColumnType("int");

                    b.Property<int>("LegacyTopicId")
                        .HasColumnType("int");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartedByDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StartedByLegacyUserId")
                        .HasColumnType("int");

                    b.Property<bool?>("StartedByUserValidated")
                        .HasColumnType("bit");

                    b.Property<int>("StarterAttachCount")
                        .HasColumnType("int");

                    b.Property<string>("StarterAttachment")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("StarterFileSize")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LegacyTopicId")
                        .IsUnique()
                        .HasDatabaseName("UQ_ModernForumThread_LegacyTopicId");

                    b.ToTable("ModernForumThread", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("QueenZone.Data.Entities.NewsAgentDraftEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AiRunId")
                        .HasColumnType("int");

                    b.Property<string>("AttributionText")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("ConfidenceNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProposedBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProposedExcerpt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ProposedSlug")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProposedTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("SuggestedPublishAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AiRunId");

                    b.HasIndex("CandidateId")
                        .IsUnique()
                        .HasDatabaseName("IX_NewsAgentDrafts_CandidateId");

                    b.ToTable("NewsAgentDrafts", (string)null);
                });

            modelBuilder.Entity("QueenZone.Data.Entities.NewsAgentRunLeaseEntity", b =>
                {
                    b.Property<string>("LeaseName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("AcquiredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("HolderId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("LeaseName");

                    b.ToTable("NewsAgentRunLeases", (string)null);
                });

            modelBuilder.Entity("QueenZone.Data.Entities.NewsAiRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("EstimatedCostUsd")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<int?>("InputTokens")
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ModelProvider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("OutputTokens")
                        .HasColumnType("int");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StructuredResultJson")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId", "StartedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_NewsAiRuns_CandidateId_StartedAt");

                    b.ToTable("NewsAiRuns", (string)null);
                });

            modelBuilder.Entity("QueenZone.Data.Entities.NewsAuditLogEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("NewsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("NewsId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_NewsAuditLog_NewsId_OccurredAt");

                    b.ToTable("NewsAuditLog", (string)null);
                });

            modelBuilder.Entity("QueenZone.Data.Entities.NewsCandidateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("CanonicalUrlHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DiscoveredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DuplicateOfCandidateId")
                        .HasColumnType("int");

                    b.Property<int?>("PromotedNewsId")
                        .HasColumnType("int");

                    b.Property<decimal?>("RelevanceScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SourcePublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SourceTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CanonicalUrlHash")
                        .IsUnique()
                        .HasDatabaseName("IX_NewsCandidates_CanonicalUrlHash");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("IX_NewsCandidates_ContentHash");

                    b.HasIndex("DuplicateOfCandidateId");

                    b.HasIndex("SourceId");

                    b.HasIndex("Status", "DiscoveredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_NewsCandidates_Status_DiscoveredAt");

                    b.ToTable("NewsCandidates", (string)null);
                });

            modelBuilder.Entity("QueenZone.Data.Entities.NewsCandidateEvidenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CandidateId")
                        .HasColumnType("int");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Etag")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FetchedPublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FetchedTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceTrustTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId", "FetchedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_NewsCandidateEvidence_CandidateId_FetchedAt");

                    b.ToTable("NewsCandidateEvidence", (string)null);
                });

            modelBuilder.Entity("QueenZone.Data.Entities.NewsDiscoverySourceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("FeedOrSiteUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("HomepageUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PollIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("RelevanceKeywords")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrustTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("IX_NewsDiscoverySources_Key");

                    b.ToTable("NewsDiscoverySources", (string)null);
                });

            modelBuilder.Entity("QueenZone.Data.Entities.NewsTableRow", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NEWS_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsId"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ARTICLE");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("EditorEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("EDITOR_EMAIL");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)")
                        .HasColumnName("EXCERPT");

                    b.Property<int>("IsPublished")
                        .HasColumnType("int")
                        .HasColumnName("DISPLAY");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATE");

                    b.Property<int>("QueenOnline")
                        .HasColumnType("int")
                        .HasColumnName("QUEEN_ONLINE");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("SLUG");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("SOURCE_URL");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("TITLE");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("TYPE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UPDATED_AT");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("USER_ID");

                    b.HasKey("NewsId");

                    b.ToTable("NEWS_T", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("QueenZone.Data.Entities.PhotoSubmissionAuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("PhotoSubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PhotoSubmissionId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_PhotoSubmissionAuditLog_Submission_OccurredAt");

                    b.ToTable("PhotoSubmissionAuditLog", (string)null);
                });

            modelBuilder.Entity("QueenZone.Data.Entities.PhotoSubmissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApprovedCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("ApproximateDate")
                        .HasColumnType("date");

                    b.Property<int?>("ApproximateYear")
                        .HasColumnType("int");

                    b.Property<string>("BlobPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int?>("ImageHeightPx")
                        .HasColumnType("int");

                    b.Property<int?>("ImageWidthPx")
                        .HasColumnType("int");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReviewerEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SubmitterMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SuggestedCategory")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThumbnailBlobPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("WebOptimizedBlobPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.HasIndex("Status", "SubmittedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_PhotoSubmissions_Status_SubmittedAt");

                    b.HasIndex("SubmitterMemberId", "SubmittedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_PhotoSubmissions_Submitter_SubmittedAt");

                    b.ToTable("PhotoSubmissions", (string)null);
                });

            modelBuilder.Entity("QueenZone.Data.Entities.QueenHistoryEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DatePrecision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Importance")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SourceType", "SourceKey")
                        .IsUnique()
                        .HasDatabaseName("IX_QueenHistoryEvents_Source");

                    b.HasIndex("IsPublished", "DatePrecision", "EventDate")
                        .HasDatabaseName("IX_QueenHistoryEvents_Published_Date");

                    b.ToTable("QueenHistoryEvents", (string)null);
                });

            modelBuilder.Entity("QueenZone.Data.Entities.ForumPollEntity", b =>
                {
                    b.HasOne("QueenZone.Data.Entities.ModernForumThreadEntity", "Thread")
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("QueenZone.Data.Entities.ForumPollOptionEntity", b =>
                {
                    b.HasOne("QueenZone.Data.Entities.ForumPollEntity", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("QueenZone.Data.Entities.ForumPollVoteEntity", b =>
                {
                    b.HasOne("QueenZone.Data.Entities.ForumPollOptionEntity", "Option")
                        .WithMany("Votes")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QueenZone.Data.Entities.ForumPollEntity", "Poll")
                        .WithMany("Votes")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("QueenZone.Data.Entities.ForumPostAttachmentEntity", b =>
                {
                    b.HasOne("QueenZone.Data.Entities.ModernForumPostEntity", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("QueenZone.Data.Entities.MemberExternalLogin", b =>
                {
                    b.HasOne("QueenZone.Data.Entities.MemberAccount", null)
                        .WithMany()
                        .HasForeignKey("MemberAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QueenZone.Data.Entities.ModernForumPostEntity", b =>
                {
                    b.HasOne("QueenZone.Data.Entities.ModernForumThreadEntity", "Thread")
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("QueenZone.Data.Entities.ModernForumThreadEntity", b =>
                {
                    b.HasOne("QueenZone.Data.Entities.ModernForumCategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("QueenZone.Data.Entities.NewsAgentDraftEntity", b =>
                {
                    b.HasOne("QueenZone.Data.Entities.NewsAiRunEntity", "AiRun")
                        .WithMany()
                        .HasForeignKey("AiRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QueenZone.Data.Entities.NewsCandidateEntity", "Candidate")
                        .WithOne("Draft")
                        .HasForeignKey("QueenZone.Data.Entities.NewsAgentDraftEntity", "CandidateId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("AiRun");

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("QueenZone.Data.Entities.NewsAiRunEntity", b =>
                {
                    b.HasOne("QueenZone.Data.Entities.NewsCandidateEntity", "Candidate")
                        .WithMany("AiRuns")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("QueenZone.Data.Entities.NewsCandidateEntity", b =>
                {
                    b.HasOne("QueenZone.Data.Entities.NewsCandidateEntity", "DuplicateOfCandidate")
                        .WithMany()
                        .HasForeignKey("DuplicateOfCandidateId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QueenZone.Data.Entities.NewsDiscoverySourceEntity", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DuplicateOfCandidate");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("QueenZone.Data.Entities.NewsCandidateEvidenceEntity", b =>
                {
                    b.HasOne("QueenZone.Data.Entities.NewsCandidateEntity", "Candidate")
                        .WithMany("Evidence")
                        .HasForeignKey("CandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");
                });

            modelBuilder.Entity("QueenZone.Data.Entities.PhotoSubmissionAuditLogEntity", b =>
                {
                    b.HasOne("QueenZone.Data.Entities.PhotoSubmissionEntity", "Submission")
                        .WithMany("AuditLogs")
                        .HasForeignKey("PhotoSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("QueenZone.Data.Entities.PhotoSubmissionEntity", b =>
                {
                    b.HasOne("QueenZone.Data.Entities.MemberAccount", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmitterMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("QueenZone.Data.Entities.ForumPollEntity", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("QueenZone.Data.Entities.ForumPollOptionEntity", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("QueenZone.Data.Entities.NewsCandidateEntity", b =>
                {
                    b.Navigation("AiRuns");

                    b.Navigation("Draft");

                    b.Navigation("Evidence");
                });

            modelBuilder.Entity("QueenZone.Data.Entities.PhotoSubmissionEntity", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
