@echo off
setlocal EnableExtensions
cd /d "%~dp0.."

title QueenZone News Agent gather + triage

echo.
echo QueenZone News Agent - gather and triage
echo ======================================
echo.
echo This run will:
echo   1. Seed discovery sources if needed
echo   2. Fetch configured public news sources
echo   3. Run initial OpenRouter triage
echo.
echo It will NOT generate news drafts.
echo.

where dotnet >nul 2>&1
if errorlevel 1 (
    echo ERROR: dotnet SDK not found. Install from https://dotnet.microsoft.com/download
    goto :fail
)

set "LOCAL_SETTINGS=src\QueenZone.NewsAgent.Worker\appsettings.Local.json"
set "EXAMPLE=src\QueenZone.NewsAgent.Worker\appsettings.Local.json.example"

if not exist "%LOCAL_SETTINGS%" (
    if "%OPENROUTER_API_KEY%"=="" (
        echo ERROR: %LOCAL_SETTINGS% not found and OPENROUTER_API_KEY is not set.
        echo Copy %EXAMPLE% to %LOCAL_SETTINGS% and set OpenRouter:ApiKey.
        echo Set ConnectionStrings:QueenZoneLegacy there too if you want persisted review-queue results.
        goto :fail
    )
)

if exist "%LOCAL_SETTINGS%" (
    findstr /C:"sk-or-v1-..." "%LOCAL_SETTINGS%" >nul 2>&1
    if not errorlevel 1 (
        if "%OPENROUTER_API_KEY%"=="" (
            echo ERROR: OpenRouter API key still looks like the example placeholder.
            echo Edit %LOCAL_SETTINGS% and set OpenRouter:ApiKey, or set OPENROUTER_API_KEY.
            goto :fail
        )
    )
)

echo Running discovery fetch plus triage only...
echo.
dotnet run --project src\QueenZone.NewsAgent.Worker -- discover-news --seed-sources --triage
set EXITCODE=%ERRORLEVEL%

echo.
if %EXITCODE% equ 0 (
    echo Gather and triage completed.
    echo Review candidates at /admin/news-discovery. Drafts were not generated by this script.
) else (
    echo Gather and triage failed with exit code %EXITCODE%.
)

goto :end

:fail
set EXITCODE=1

:end
echo.
pause
exit /b %EXITCODE%
